example/example/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/gallery/urls.py
from django.conf.urls import url

from clean_urls.views import CleanURLHandler

from .models import Photographer, Category, Photo
from .views import HomeView, PhotographerView, CategoryView, PhotoView


app_name = 'gallery'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),  # home page - just to show list of photographers
    url(
        r'^(?P<slug>([-\w]+/)+)$',  # very generic regex
        CleanURLHandler(  # this class will do all dirty work for us
            (Photographer.objects.all(), PhotographerView.as_view()),  # clean url will start with Photographer's slug and call PhotographerView
            (Category.objects.all(), CategoryView.as_view()),  # here we state that Photographer may contain a Category within
            (Photo.objects.all(), PhotoView.as_view()),  # and Category may contain Photos within
            # ... don't stop! :)
        ),
        name='generic'  # needed for reverse url resolution; call it "generic" because this url can point to different objects
    ),
]

example/gallery/models.py
from django.core.urlresolvers import reverse
from django.db import models

from mptt.models import MPTTModel, TreeForeignKey


class Photographer(models.Model):
    image = models.ImageField('image')
    slug = models.SlugField()

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('gallery:generic', kwargs={'slug': self.get_slug()})  # CleanURLHandler automatically created 'get_slug' method; for this simple model it will just return self.slug

    def get_categories(self):
        return Category.objects.root_nodes().filter(photographer=self)


class Category(MPTTModel):
    photographer = models.ForeignKey('Photographer')
    parent = TreeForeignKey('self', blank=True, null=True)
    slug = models.CharField('slug', max_length=32)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('gallery:generic', kwargs={'slug': self.get_slug()})

    def get_photos(self):
        return Photo.objects.filter(categories=self)


class Photo(models.Model):
    categories = models.ManyToManyField('Category')
    image = models.ImageField('image')
    slug = models.SlugField()

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse('gallery:generic', kwargs={'slug': self.get_slug()})

    def get_parent(self):
        return self.categories.first()  # by default, the first category will be treated as parent

example/gallery/views.py
from django.views.generic import DetailView, ListView

from .models import Photographer


class HomeView(ListView):
    model = Photographer

    template_name = 'gallery/home.html'


class PhotographerView(DetailView):
    template_name = 'gallery/photographer.html'

    def dispatch(self, *args, **kwargs):  # already resolved instance here!
        self.instance = kwargs.pop('instance')  # save instance
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.instance  # use saved instance


class CategoryView(DetailView):
    template_name = 'gallery/category.html'

    def dispatch(self, *args, **kwargs):
        self.instance = kwargs.pop('instance')
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.instance


class PhotoView(DetailView):
    template_name = 'gallery/photo.html'

    def dispatch(self, *args, **kwargs):
        self.instance = kwargs.pop('instance')
        return super().dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.instance

example/gallery/templates/gallery/base.html
<small>Powered by <a href="https://github.com/c0ntribut0r/django-clean-urls">django-clean-urls</a></small>
<hr>

<div style="background-color: #FAFAFA;">
    Breadcrumbs:
    <a href="{% url 'gallery:home' %}">Home</a>
    {% for ancestor in object.get_parents %}
        / <a href="{{ ancestor.get_absolute_url }}">{{ ancestor }}</a>
    {% endfor %}
</div>
<h4>{% block title %}{% endblock %}</h4>
{% block content %}{% endblock %}

example/gallery/templates/gallery/category.html
{% extends 'gallery/base.html' %}

{% block title %}
    {{ object.slug|upper }} (Category)
{% endblock %}

{% block content %}
    {{ object.slug }}'s subcategories:
    <ul>
        {% for category in object.get_children %}
            <li><a href="{{ category.get_absolute_url }}">{{ category.slug }}</a></li>
        {% empty %}
            <li>--</li>
        {% endfor %}
    </ul>

    {{ object.slug }}'s photos:
    <ul>
        {% for photo in object.get_photos %}
            <li>
                <a href="{{ photo.get_absolute_url }}"><img src="/media/{{ photo.image }}" width="100"></a>
            </li>
        {% empty %}
            <li>
                --
            </li>
        {% endfor %}
    </ul>
{% endblock %}

example/gallery/templates/gallery/home.html
{% extends 'gallery/base.html' %}

{% block title %}
    Photographers
{% endblock %}

{% block content %}
    <table>
        <tr>
            {% for photographer in object_list %}
                <td align="center">
                    <a href="{{ photographer.get_absolute_url }}">
                        <img src="/media/{{ photographer.image }}"><br>
                        {{ photographer.slug }}
                    </a>
                </td>
            {% endfor %}
        </tr>
    </table>
{% endblock %}

example/gallery/templates/gallery/photo.html
{% extends 'gallery/base.html' %}

{% block title %}
    {{ object.slug|upper }} (Photo)
{% endblock %}

{% block content %}
    <img src="/media/{{ photo.image }}">
{% endblock %}

example/gallery/templates/gallery/photographer.html
{% extends 'gallery/base.html' %}

{% block title %}
    {{ object.slug|upper }}<br>
    <small>Photographer</small>
{% endblock %}

{% block content %}
    <a href="{% url 'gallery:home' %}">< Back to all photographers</a>
{% endblock %}